apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegistwin.fullname" . }}-secrets
  labels:
    {{- include "aegistwin.labels" . | nindent 4 }}
type: Opaque
stringData:
  neo4j-password: {{ .Values.neo4j.auth.defaultPassword | quote }}
  postgres-password: {{ .Values.postgresql.auth.defaultPassword | quote }}
  jwt-secret: {{ .Values.security.jwtSecret | quote }}
  encryption-key: {{ .Values.security.encryptionKey | quote }}
