import { TopologyNode, TopologyEdge, RiskSummary, SimulationStep, RemediationSuggestion, TelemetryLogEvent, ComplianceStandard, AuditRecord } from "./types";

export const INITIAL_NODES: TopologyNode[] = [
  {
    id: "gw-external",
    label: "Edge Border Gateway",
    hostname: "gw-ext-01.aegis.grid",
    ip: "198.51.100.1",
    tier: "DMZ",
    type: "Gateway",
    os: "VyOS Linux 1.4-LTS",
    criticality: 6.0,
    compromised: false,
    services: ["BGP/179", "IPsec/500", "SNMP/161"],
    vulnerabilities: [],
    metrics: { temperature: 38.4, voltage: 228.6, packetDropRate: 0.01, cpuLoad: 24, memoryUsage: 41, latencyMs: 2.1, throughputMbps: 1240 },
    lastSeen: "2s ago",
    tags: ["Perimeter", "BGP-Border", "Hardware-Appliance"],
  },
  {
    id: "web-dmz-01",
    label: "Reverse Proxy DMZ",
    hostname: "web-dmz-01.aegis.grid",
    ip: "10.0.1.10",
    tier: "DMZ",
    type: "Proxy",
    os: "Alpine Linux 3.19",
    criticality: 6.5,
    compromised: false,
    services: ["HTTP/80", "HTTPS/443", "TLS-Terminator"],
    vulnerabilities: [
      {
        cve: "CVE-2023-38606",
        title: "Nginx Request Smuggling & Header Injection",
        cvss: 7.5,
        mitre: "T1190",
        description: "Allows HTTP request desynchronization via chunked transfer-encoding flaw."
      }
    ],
    metrics: { temperature: 41.2, voltage: 230.1, packetDropRate: 0.03, cpuLoad: 38, memoryUsage: 54, latencyMs: 3.4, throughputMbps: 840 },
    lastSeen: "1s ago",
    tags: ["DMZ", "LoadBalancer", "SSL-Offloader"],
  },
  {
    id: "vpn-gateway",
    label: "Industrial SSL-VPN Gateway",
    hostname: "vpn-ot-01.aegis.grid",
    ip: "10.0.1.15",
    tier: "DMZ",
    type: "VPN",
    os: "FortiOS 7.0.12",
    criticality: 8.5,
    compromised: false,
    services: ["HTTPS/443", "IKEv2/500", "RADIUS/1812"],
    vulnerabilities: [
      {
        cve: "CVE-2023-27997",
        title: "FortiOS SSL-VPN Heap Buffer Overflow RCE",
        cvss: 9.8,
        mitre: "T1190",
        description: "Pre-authentication remote code execution flaw in SSL-VPN core daemon."
      }
    ],
    metrics: { temperature: 45.8, voltage: 231.2, packetDropRate: 0.14, cpuLoad: 68, memoryUsage: 79, latencyMs: 6.8, throughputMbps: 420 },
    lastSeen: "Just now",
    tags: ["RemoteAccess", "ZeroTrust-Gateway", "MFA-Enforced"],
  },
  {
    id: "web-app-01",
    label: "OT Scada Web Portal",
    hostname: "portal-web-01.aegis.internal",
    ip: "10.0.2.20",
    tier: "Web Tier",
    type: "Web Server",
    os: "Debian 12 Bookworm",
    criticality: 7.0,
    compromised: false,
    services: ["Node.js/3000", "Nginx/80", "WebSocket/8080"],
    vulnerabilities: [
      {
        cve: "CVE-2021-44228",
        title: "Log4Shell Remote Code Execution",
        cvss: 10.0,
        mitre: "T1190",
        description: "JNDI LDAP deserialization vulnerability executing arbitrary bytecode."
      }
    ],
    credentials: ["portal_api_token"],
    metrics: { temperature: 43.1, voltage: 229.8, packetDropRate: 0.02, cpuLoad: 49, memoryUsage: 63, latencyMs: 4.1, throughputMbps: 610 },
    lastSeen: "3s ago",
    tags: ["Operator-HMI", "Web-Front"],
  },
  {
    id: "api-gateway",
    label: "Internal Envoy API Gateway",
    hostname: "api-gw-01.aegis.internal",
    ip: "10.0.2.25",
    tier: "Web Tier",
    type: "API Gateway",
    os: "Ubuntu 22.04 LTS",
    criticality: 7.5,
    compromised: false,
    services: ["gRPC/50051", "HTTPS/8443", "mTLS/9443"],
    vulnerabilities: [],
    metrics: { temperature: 40.5, voltage: 230.0, packetDropRate: 0.01, cpuLoad: 31, memoryUsage: 48, latencyMs: 1.8, throughputMbps: 1120 },
    lastSeen: "Just now",
    tags: ["mTLS-Mesh", "ServiceBus"],
  },
  {
    id: "app-srv-01",
    label: "Turbine Telemetry Aggregator",
    hostname: "turbine-agg-01.aegis.internal",
    ip: "10.0.3.30",
    tier: "App Tier",
    type: "Application Server",
    os: "Red Hat Enterprise 9.2",
    criticality: 8.0,
    compromised: false,
    services: ["ActiveMQ/61616", "MQTT/1883", "Prometheus/9090"],
    vulnerabilities: [
      {
        cve: "CVE-2023-46604",
        title: "Apache ActiveMQ OpenWire Remote Code Execution",
        cvss: 9.8,
        mitre: "T1190",
        description: "Arbitrary class instantiation during OpenWire serialization payload."
      }
    ],
    metrics: { temperature: 47.9, voltage: 230.5, packetDropRate: 0.05, cpuLoad: 64, memoryUsage: 71, latencyMs: 5.2, throughputMbps: 540 },
    lastSeen: "2s ago",
    tags: ["OT-Telemetry", "MessageBroker"],
  },
  {
    id: "ci-cd-runner",
    label: "Firmware Build & Deploy Node",
    hostname: "ci-firmware-01.aegis.internal",
    ip: "10.0.3.40",
    tier: "App Tier",
    type: "CI/CD Worker",
    os: "Ubuntu 22.04 LTS",
    criticality: 8.5,
    compromised: false,
    services: ["Docker/2375", "Jenkins/8080", "SSH/22"],
    vulnerabilities: [
      {
        cve: "CVE-2024-23897",
        title: "Jenkins CLI Arbitrary File Read Flaw",
        cvss: 9.8,
        mitre: "T1190",
        description: "args4j parser vulnerability extracting secret cryptographic keys and SSH credentials."
      }
    ],
    credentials: ["docker_registry_token", "github_deploy_key"],
    metrics: { temperature: 51.2, voltage: 232.0, packetDropRate: 0.08, cpuLoad: 77, memoryUsage: 84, latencyMs: 6.1, throughputMbps: 390 },
    lastSeen: "1s ago",
    tags: ["SupplyChain", "DevSecOps", "HighPrivilege"],
  },
  {
    id: "admin-workstation-01",
    label: "OT SecOps Jumpbox / Bastion",
    hostname: "secops-jump-01.aegis.internal",
    ip: "10.0.4.50",
    tier: "App Tier",
    type: "Workstation",
    os: "Windows 11 Pro Enterprise",
    criticality: 9.0,
    compromised: false,
    services: ["RDP/3389", "WinRM/5985", "CrowdStrike-Agent"],
    vulnerabilities: [],
    credentials: ["cached_domain_admin_kerberos_ticket", "local_admin_hash"],
    metrics: { temperature: 39.8, voltage: 229.4, packetDropRate: 0.01, cpuLoad: 28, memoryUsage: 51, latencyMs: 2.8, throughputMbps: 210 },
    lastSeen: "Just now",
    tags: ["Bastion", "Tier-1-Admin", "Crown-Jewel-Adjacent"],
  },
  {
    id: "plc-rtu-substation",
    label: "Substation RTU Siemens S7-1500",
    hostname: "plc-sub-north.aegis.ot",
    ip: "192.168.10.12",
    tier: "OT/ICS Zone",
    type: "PLC Controller",
    os: "Siemens Simatic Firmware v2.9",
    criticality: 9.5,
    compromised: false,
    services: ["S7comm/102", "Modbus-TCP/502", "PROFINET/34964"],
    vulnerabilities: [
      {
        cve: "CVE-2022-38465",
        title: "Siemens S7 Authentication & Integrity Bypass",
        cvss: 8.8,
        mitre: "T0814",
        description: "Hardcoded cryptographic key flaw allowing unauthorized control commands to turbine coils."
      }
    ],
    metrics: { temperature: 54.3, voltage: 24.1, packetDropRate: 0.01, cpuLoad: 34, memoryUsage: 45, latencyMs: 1.2, throughputMbps: 45 },
    lastSeen: "Just now",
    tags: ["OT-Physical", "Purdue-Level-1", "Grid-Protection"],
  },
  {
    id: "scada-historian-01",
    label: "OSIsoft PI SCADA Historian",
    hostname: "pi-historian-01.aegis.ot",
    ip: "192.168.10.20",
    tier: "OT/ICS Zone",
    type: "SCADA Historian",
    os: "Windows Server 2022 OT",
    criticality: 9.0,
    compromised: false,
    services: ["PI-API/5450", "OPC-UA/4840", "MSSQL/1433"],
    vulnerabilities: [],
    metrics: { temperature: 46.5, voltage: 230.2, packetDropRate: 0.02, cpuLoad: 58, memoryUsage: 69, latencyMs: 3.5, throughputMbps: 310 },
    lastSeen: "Just now",
    tags: ["Purdue-Level-2", "ProcessHistorian"],
  },
  {
    id: "db-cluster-01",
    label: "PostgreSQL OT Data Lake Primary",
    hostname: "pg-primary-01.aegis.internal",
    ip: "10.0.5.60",
    tier: "DB Tier",
    type: "Database",
    os: "Rocky Linux 9",
    criticality: 8.5,
    compromised: false,
    services: ["PostgreSQL/5432", "pgBouncer/6432"],
    vulnerabilities: [],
    metrics: { temperature: 48.9, voltage: 231.0, packetDropRate: 0.01, cpuLoad: 67, memoryUsage: 82, latencyMs: 2.2, throughputMbps: 890 },
    lastSeen: "Just now",
    tags: ["ClusterPrimary", "EncryptedAtRest"],
  },
  {
    id: "corp-dc-01",
    label: "Enterprise Active Directory DC",
    hostname: "dc-root-01.aegis.corp",
    ip: "10.0.6.70",
    tier: "Active Directory",
    type: "Domain Controller",
    os: "Windows Server 2022 Core",
    criticality: 10.0,
    compromised: false,
    services: ["Kerberos/88", "LDAPS/636", "DNS/53", "SMB/445"],
    vulnerabilities: [
      {
        cve: "CVE-2021-42287",
        title: "sAMAccountName Kerberos Spoofing Privilege Escalation",
        cvss: 8.8,
        mitre: "T1068",
        description: "Allows standard domain user to escalate directly to Domain Admin via Kerberos ticket validation flaw."
      }
    ],
    credentials: ["krbtgt_hash", "ntds.dit_database"],
    metrics: { temperature: 43.4, voltage: 230.0, packetDropRate: 0.01, cpuLoad: 46, memoryUsage: 61, latencyMs: 1.5, throughputMbps: 580 },
    lastSeen: "Just now",
    tags: ["Tier-0-Identity", "CrownJewel", "PKI-Root"],
  },
  {
    id: "db-cluster-02",
    label: "HashiCorp Vault & Grid HSM",
    hostname: "vault-hsm-01.aegis.internal",
    ip: "10.0.5.61",
    tier: "DB Tier",
    type: "Key Management / Vault",
    os: "Hardened Linux MicroOS",
    criticality: 10.0,
    compromised: false,
    services: ["Vault-API/8200", "Raft/8201", "PKCS#11/HSM"],
    vulnerabilities: [],
    credentials: ["grid_root_signing_keys", "tls_ca_private_keys"],
    metrics: { temperature: 41.0, voltage: 230.4, packetDropRate: 0.00, cpuLoad: 35, memoryUsage: 44, latencyMs: 1.1, throughputMbps: 340 },
    lastSeen: "Just now",
    tags: ["Tier-0-Cryptographic", "CrownJewel", "Hardware-Root-Of-Trust"],
  }
];

export const INITIAL_EDGES: TopologyEdge[] = [
  { id: "e-gw-webdmz", source: "gw-external", target: "web-dmz-01", type: "smoothstep", port: 443, protocol: "HTTPS", status: "normal" },
  { id: "e-gw-vpn", source: "gw-external", target: "vpn-gateway", type: "smoothstep", port: 443, protocol: "SSL-VPN", status: "normal" },
  { id: "e-webdmz-webapp", source: "web-dmz-01", target: "web-app-01", type: "smoothstep", port: 80, protocol: "HTTP", status: "normal" },
  { id: "e-webdmz-apigw", source: "web-dmz-01", target: "api-gateway", type: "smoothstep", port: 8443, protocol: "mTLS", status: "normal" },
  { id: "e-vpn-admin", source: "vpn-gateway", target: "admin-workstation-01", type: "smoothstep", port: 3389, protocol: "RDP", status: "normal" },
  { id: "e-apigw-appsrv1", source: "api-gateway", target: "app-srv-01", type: "smoothstep", port: 61616, protocol: "OpenWire", status: "normal" },
  { id: "e-apigw-cicd", source: "api-gateway", target: "ci-cd-runner", type: "smoothstep", port: 8080, protocol: "HTTP", status: "normal" },
  { id: "e-appsrv1-plc", source: "app-srv-01", target: "plc-rtu-substation", type: "smoothstep", port: 502, protocol: "Modbus-TCP", status: "normal" },
  { id: "e-appsrv1-scada", source: "app-srv-01", target: "scada-historian-01", type: "smoothstep", port: 5450, protocol: "PI-API", status: "normal" },
  { id: "e-appsrv1-db1", source: "app-srv-01", target: "db-cluster-01", type: "smoothstep", port: 5432, protocol: "Postgres", status: "normal" },
  { id: "e-admin-dc", source: "admin-workstation-01", target: "corp-dc-01", type: "smoothstep", port: 445, protocol: "SMB", status: "normal" },
  { id: "e-dc-vault", source: "corp-dc-01", target: "db-cluster-02", type: "smoothstep", port: 8200, protocol: "HTTPS", status: "normal" },
  { id: "e-cicd-db1", source: "ci-cd-runner", target: "db-cluster-01", type: "smoothstep", port: 5432, protocol: "Postgres", status: "normal" },
];

export const INITIAL_RISK_SUMMARY: RiskSummary = {
  overall_score: 74.5,
  level: "HIGH",
  total_hosts: 13,
  compromised_count: 0,
  vulnerability_count: 8,
  crown_jewels_at_risk: 2,
  network_health_index: 89.2,
  throughput_mbps: 3840,
};

export const INITIAL_SIMULATION_STEPS: SimulationStep[] = [
  {
    step_number: 1,
    tactic: "Initial Access",
    technique_id: "T1190",
    technique_name: "Exploit Public-Facing Application",
    source_node: "gw-external",
    source_name: "Edge Border Gateway",
    target_node: "vpn-gateway",
    target_name: "Industrial SSL-VPN Gateway",
    target_ip: "10.0.1.15",
    action_description: "Autonomous adversary exploited CVE-2023-27997 FortiOS heap buffer overflow. Spawned interactive shell with SYSTEM privileges.",
    credentials_harvested: ["vpn_session_token", "admin_portal_cookie"],
    timestamp: "10:41:22 UTC",
    severity: "CRITICAL",
  },
  {
    step_number: 2,
    tactic: "Lateral Movement",
    technique_id: "T1021.001",
    technique_name: "Remote Desktop Protocol (RDP)",
    source_node: "vpn-gateway",
    source_name: "Industrial SSL-VPN Gateway",
    target_node: "admin-workstation-01",
    target_name: "OT SecOps Jumpbox / Bastion",
    target_ip: "10.0.4.50",
    action_description: "Pivoted across perimeter trust boundary via stolen session ticket to gain interactive terminal on Tier-1 SecOps Jumpbox.",
    credentials_harvested: ["cached_domain_admin_kerberos_ticket"],
    timestamp: "10:42:05 UTC",
    severity: "CRITICAL",
  },
  {
    step_number: 3,
    tactic: "Privilege Escalation",
    technique_id: "T1068",
    technique_name: "Exploitation for Privilege Escalation",
    source_node: "admin-workstation-01",
    source_name: "OT SecOps Jumpbox / Bastion",
    target_node: "corp-dc-01",
    target_name: "Enterprise Active Directory DC",
    target_ip: "10.0.6.70",
    action_description: "Leveraged sAMAccountName spoofing (CVE-2021-42287) using acquired Kerberos TGT to forge Domain Controller service ticket. Tier-0 compromise verified.",
    credentials_harvested: ["krbtgt_ntlm_hash", "enterprise_admin_cert"],
    timestamp: "10:42:51 UTC",
    severity: "CRITICAL",
  }
];

export const INITIAL_SUGGESTIONS: RemediationSuggestion[] = [
  {
    id: "rem-patch-vpn-cve27997",
    title: "Patch CVE-2023-27997 on Industrial SSL-VPN Gateway",
    action_type: "patch_cve",
    target_id: "vpn-gateway",
    details: { cve_id: "CVE-2023-27997" },
    category: "Vulnerability Mitigation",
    priority: "P0 - CRITICAL",
    predicted_risk_reduction: 33.3,
    mitre_reference: "M1051 (Update Software)",
    description: "Upgrade FortiOS firmware to 7.0.13+ to permanently seal unauthenticated remote heap overflow vector.",
  },
  {
    id: "rem-seg-vpn-admin",
    title: "Enforce Zero Trust Network Segmentation on Bastion",
    action_type: "block_edge",
    target_id: "vpn-gateway",
    details: { source: "vpn-gateway", target: "admin-workstation-01" },
    category: "Zero Trust Segmentation",
    priority: "P1 - HIGH",
    predicted_risk_reduction: 28.5,
    mitre_reference: "M1030 (Network Segmentation)",
    description: "Sever direct RDP route from perimeter VPN to Tier-1 SecOps jumpbox. Enforce hardware FIDO2 bastion gateway.",
  },
  {
    id: "rem-purge-admin-cred",
    title: "Purge Cached Domain Admin Ticket on Jumpbox",
    action_type: "revoke_credential",
    target_id: "admin-workstation-01",
    details: { credential_id: "cached_domain_admin_kerberos_ticket" },
    category: "Identity Defense",
    priority: "P1 - HIGH",
    predicted_risk_reduction: 22.0,
    mitre_reference: "M1026 (Privileged Account Management)",
    description: "Invalidate cached Kerberos TGT and enroll Tier-1 jumpboxes in Protected Users Active Directory group.",
  },
  {
    id: "rem-isolate-plc-bus",
    title: "Enforce IEC 62443 Deep Packet Inspection on Modbus/TCP",
    action_type: "block_edge",
    target_id: "app-srv-01",
    details: { source: "app-srv-01", target: "plc-rtu-substation" },
    category: "OT / Industrial Protocol Defense",
    priority: "P1 - HIGH",
    predicted_risk_reduction: 19.5,
    mitre_reference: "M1037 (Filter Network Traffic)",
    description: "Deploy inline ICS firewall inspecting Function Code 0x05 / 0x06 write commands to Siemens S7-1500 RTU coils.",
  },
];

export const INITIAL_TELEMETRY_LOGS: TelemetryLogEvent[] = [
  {
    id: "evt-001",
    timestamp: "11:42:01.402",
    level: "INFO",
    channel: "TELEMETRY",
    source: "plc-rtu-substation",
    ip: "192.168.10.12",
    message: "Modbus/TCP Keepalive Poll: Unit 1 Coils 0x0001-0x0040 normal. Temperature: 54.3°C, Bus Voltage: 24.1V.",
  },
  {
    id: "evt-002",
    timestamp: "11:42:03.118",
    level: "INFO",
    channel: "TOPOLOGY",
    source: "neo4j-graph-engine",
    message: "Graph synchronized: 13 active nodes, 13 verified directional edges. 0 orphan nodes.",
  },
  {
    id: "evt-003",
    timestamp: "11:42:05.882",
    level: "WARN",
    channel: "SECURITY",
    source: "web-dmz-01",
    ip: "10.0.1.10",
    message: "Anomalous HTTP header length detected in incoming request from external ASN 15169. Matched CVE-2023-38606 heuristic.",
    mitre: "T1190",
  },
  {
    id: "evt-004",
    timestamp: "11:42:08.520",
    level: "CRITICAL",
    channel: "SIMULATION",
    source: "vpn-gateway",
    ip: "10.0.1.15",
    message: "Adversary AI exploited FortiOS SSL-VPN buffer overflow (CVE-2023-27997). Interactive shell spawned.",
    mitre: "T1190",
  },
  {
    id: "evt-005",
    timestamp: "11:42:10.991",
    level: "CRITICAL",
    channel: "SIMULATION",
    source: "admin-workstation-01",
    ip: "10.0.4.50",
    message: "RDP session lateral pivot initiated from vpn-gateway. Kerberos ticket cache extraction observed.",
    mitre: "T1021.001",
  },
  {
    id: "evt-006",
    timestamp: "11:42:13.204",
    level: "WARN",
    channel: "SOAR",
    source: "soar-dispatcher",
    message: "SOAR automated playbook triggered: Playbook-PB-884 (VPN Containment). Awaiting SecOps analyst authorization.",
  },
  {
    id: "evt-007",
    timestamp: "11:42:15.012",
    level: "INFO",
    channel: "TELEMETRY",
    source: "scada-historian-01",
    ip: "192.168.10.20",
    message: "Historian data ingestion at 8,420 tags/sec. Compression ratio 4.8:1. Storage health optimal.",
  }
];

export const INITIAL_COMPLIANCE_STANDARDS: ComplianceStandard[] = [
  {
    id: "iec-62443",
    name: "IEC 62443-3-3 Industrial Automation & Control Systems",
    version: "Security Level 3 (SL-3)",
    score: 84.5,
    level: "PASS",
    passedControls: 38,
    totalControls: 45,
    keyControls: [
      { controlId: "SR 1.1", title: "Human User Identification & Authentication", status: "COMPLIANT" },
      { controlId: "SR 1.2", title: "Software Process & Device Identification", status: "COMPLIANT" },
      { controlId: "SR 3.1", title: "Communication Integrity (Modbus/OPC)", status: "PARTIAL", remediationTarget: "plc-rtu-substation" },
      { controlId: "SR 5.1", title: "Network Segmentation (Purdue Model)", status: "NON_COMPLIANT", remediationTarget: "vpn-gateway" },
      { controlId: "SR 7.6", title: "Network & Security Configuration Verification", status: "COMPLIANT" },
    ],
  },
  {
    id: "nist-csf-2",
    name: "NIST Cybersecurity Framework 2.0",
    version: "Core Functions: GOVERN, IDENTIFY, PROTECT, DETECT, RESPOND, RECOVER",
    score: 79.0,
    level: "WARN",
    passedControls: 62,
    totalControls: 78,
    keyControls: [
      { controlId: "PR.AC-05", title: "Network Integrity & Protected Remote Access", status: "NON_COMPLIANT", remediationTarget: "vpn-gateway" },
      { controlId: "DE.CM-01", title: "Network Monitoring to Detect Potential Adverse Events", status: "COMPLIANT" },
      { controlId: "PR.DS-01", title: "Data-at-Rest & In-Transit Protected with Vault HSM", status: "COMPLIANT" },
      { controlId: "RS.MI-01", title: "Incidents are Contained & Lateral Propagation Quarantined", status: "PARTIAL" },
    ],
  },
  {
    id: "soc-2-type-2",
    name: "AICPA SOC 2 Type II Trust Services Criteria",
    version: "Security, Confidentiality & Availability",
    score: 91.2,
    level: "PASS",
    passedControls: 42,
    totalControls: 46,
    keyControls: [
      { controlId: "CC6.1", title: "Logical Access Controls & Role-Based Access (ABAC)", status: "COMPLIANT" },
      { controlId: "CC6.6", title: "Perimeter Boundary Defense & Firewalls", status: "PARTIAL", remediationTarget: "gw-external" },
      { controlId: "CC7.2", title: "Vulnerability Scanning & Automated Remediation", status: "COMPLIANT" },
      { controlId: "CC8.1", title: "Cryptographic Tamper-Proof Change Authorization", status: "COMPLIANT" },
    ],
  },
];

export const INITIAL_AUDIT_BLOCKS: AuditRecord[] = [
  {
    block_index: 0,
    timestamp: "2026-10-09T08:00:00Z",
    event_type: "GENESIS_BLOCK",
    tenant_id: "tenant-na-ics-grid",
    actor: "system:kernel",
    action: "LEDGER_INITIALIZE",
    target_resource: "system:root",
    previous_hash: "0000000000000000000000000000000000000000000000000000000000000000",
    block_hash: "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    is_valid: true,
  },
  {
    block_index: 1,
    timestamp: "2026-10-09T08:15:32Z",
    event_type: "TOPOLOGY_SEED",
    tenant_id: "tenant-na-ics-grid",
    actor: "secops.lead@aegistwin.corp",
    action: "IMPORT_ASSET_GRAPH",
    target_resource: "graph:neo4j:grid-topology-v2",
    previous_hash: "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    block_hash: "c298fe63c87e87b7a1f59993351be978e88e89408b068ab38c823da24a7337a8",
    is_valid: true,
  },
  {
    block_index: 2,
    timestamp: "2026-10-09T09:30:10Z",
    event_type: "POLICY_ENFORCEMENT",
    tenant_id: "tenant-na-ics-grid",
    actor: "opa.engine@aegistwin.corp",
    action: "ABAC_RULE_EVALUATE",
    target_resource: "tenant:north-america-ics:assets",
    previous_hash: "c298fe63c87e87b7a1f59993351be978e88e89408b068ab38c823da24a7337a8",
    block_hash: "9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca7",
    is_valid: true,
  },
  {
    block_index: 3,
    timestamp: "2026-10-09T10:41:22Z",
    event_type: "ADVERSARY_SIMULATION",
    tenant_id: "tenant-na-ics-grid",
    actor: "agent:autonomous_red_team",
    action: "EXECUTE_EXPLOIT_STEP",
    target_resource: "node:vpn-gateway",
    previous_hash: "9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca7",
    block_hash: "315f5bdb76d078c43b8ac0064e4a0164612b1fce77c869345bfc94c75894edd3",
    is_valid: true,
  },
  {
    block_index: 4,
    timestamp: "2026-10-09T11:22:45Z",
    event_type: "REMEDIATION_DISPATCH",
    tenant_id: "tenant-na-ics-grid",
    actor: "soar:playbook_dispatcher",
    action: "POST_WEBHOOK_QUARANTINE",
    target_resource: "edge:vpn-gateway->admin-workstation-01",
    previous_hash: "315f5bdb76d078c43b8ac0064e4a0164612b1fce77c869345bfc94c75894edd3",
    block_hash: "ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d",
    is_valid: true,
  },
];

export const TENANTS_LIST = [
  { id: "tenant-na-ics-grid", name: "North America ICS Power Grid", region: "US-East / ERCOT", status: "ACTIVE", assetsCount: 13, criticalThreats: 1 },
  { id: "tenant-emea-substation", name: "EMEA High-Voltage Substation Twin", region: "EU-Central / ENTSO-E", status: "ACTIVE", assetsCount: 28, criticalThreats: 0 },
  { id: "tenant-apac-refinery", name: "APAC Petrochemical Refining OT", region: "AP-Southeast / Singapore", status: "MAINTENANCE", assetsCount: 42, criticalThreats: 2 },
];
